services:
  db:
    image: postgres:16
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - TestNetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: 'backend'
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - TestNetwork
    env_file:
      - ".env"
    depends_on:
      - db

networks:
  TestNetwork:
    external: true

volumes:
  postgres_data: