# Generated by Django 5.0.1 on 2024-01-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SENDER_FULL_NAME', models.CharField(max_length=100)),
                ('RECIPIENT_FULL_NAME', models.CharField(max_length=100)),
                ('SENDING_POINT', models.CharField(max_length=100)),
                ('RECEIVING_POINT', models.CharField(max_length=100)),
                ('SENDING_INDEX', models.IntegerField()),
                ('RECEIVING_INDEX', models.IntegerField()),
                ('LETTER_TYPE', models.IntegerField(choices=[(1, 'Common'), (2, 'Registered'), (3, 'Valuable'), (4, 'Express')])),
                ('LETTER_WEIGHT', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SENDER_FULL_NAME', models.CharField(max_length=100)),
                ('RECIPIENT_FULL_NAME', models.CharField(max_length=100)),
                ('SENDING_POINT', models.CharField(max_length=100)),
                ('RECEIVING_POINT', models.CharField(max_length=100)),
                ('SENDING_INDEX', models.IntegerField()),
                ('RECEIVING_INDEX', models.IntegerField()),
                ('NOTIFY_PHONE', models.CharField(max_length=20)),
                ('PARCEL_TYPE', models.IntegerField(choices=[(1, 'Small packet'), (2, 'Parcel'), (3, '1st class parcel'), (4, 'Valuable parcel'), (5, 'International parcel'), (6, 'Express parcel')])),
                ('PAYMENT_AMOUNT', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
